apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBgHi1BTwtOciVfhajQ1SDOE7bEEF+FvY5c3cJSVK0qBOR7m1JQnSvVFe54aAuSHnFjW68E9OcMkNIcpDqnIq1Lx5UcMKAI9CRtbjbu0PYJ5NIHALQThm066nTsd8tDwErj05T95Pi2S1H0XFnSoOihi5MarkjBqa6jW3OgiZIHdiPnz15Unom7FlCwaUKhc1CG7PG3z1P9H++9CkApufhzkPS/7ifivG5U2NNdpFFalASxplL6G6iuY578Kpp8QEQe9MKQ+CJy+sE68zm64E3THYw1uI/slyy50efk98jtbV0+PaAhD10/cOHkvm9+1GhiVlYa8MWR43Oj5Z4hlo5i/qkCT8tbJ2J1L/6opqpvKEnEef/xJfKyPfmW7s8jzXegsVpmonTmUIl443epM3TPSRn6jdL49uiL/0mIdMFLlaLEg1ZnEGrJW+dn35qRvHnW1a/ulmsDXMg4K1rDVnhSTLp1Sw4UBVevBagpWG48J0OMZcoPFs21x1StQ99MvRvFq8i7sHG50MJrQ05SILO8dni7W6do2ATy2R6Pku2VG42BqqfjMOV1pAK4PAFbdjBeBFV0TTxSOnoG+CP2gdv8yvnXCajGnorXbcbxHDmGITXeMRGpaFQ4oh4kcL3N4Qp87zO1zI7Zj69Djxp8mlZLVDWoUMy1yT+NgIXu7i3+l6gB8h7c0cItmXlN4cis3svixU5Mpo9ymWCAKEy5y0PUM+vNGS7fs/SuVx2QDJnbXlxEkNqbvVuzNPVM8eGgO00HqsaPD/hy7zEwr5HVLJCYPq4hizQ4YJjbq9c4YHKhq7r4zMVg4pIEwgoaiw7tXX2gM4I8YMsKir6DdAUvO8SrpAd6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

