apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: eks-cluster-composition
  annotations:
    provider: aws
spec:
  crossplane:
    version: '>=v1.0.0'
  dependsOn:
    - provider: public.ecr.aws/seb-demo/crossplane-provider-aws
      #- provider: public.ecr.aws/awsvijisarathy/crossplane-provider-aws
      #https://github.com/crossplane/provider-aws/blob/master/cluster/UPGRADE.md#upgrade-from-v021x-to-v022x
      version: '>=v0.17.0'
