---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: applications

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apprunner
  namespace: applications

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apprunner-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: apprunner
  namespace: applications 


