---
apiVersion: v1
kind: Namespace
metadata:
  name: applications

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apprunner
  namespace: applications

---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apprunner-rolebinding
  namespace: flux-system  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: apprunner
  namespace: applications 

---
apiVersion: v1
kind: Namespace
metadata:
  name: golang

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apprunner-rolebinding
  namespace: golang  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: apprunner
  namespace: applications 

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apprunner-rolebinding
  namespace: monitoring  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: apprunner
  namespace: applications   

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apprunner-role
rules:
- apiGroups: 
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups: 
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - watch
  - create  
  - bind
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - ingresses
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses/status
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apprunner-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apprunner-role
subjects:
- kind: ServiceAccount
  name: apprunner
  namespace: applications   