apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-helmrelease
  namespace: flux-system
spec:
  targetNamespace: monitoring
  releaseName: prometheus-for-amp
  interval: 5m
  kubeConfig:
    secretRef:
      name: remote-kubeconfig    
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-configmap


