apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-for-amp
  namespace: monitoring
spec:
  releaseName: prometheus-for-amp
  interval: 5m
  kubeConfig:
    secretRef:
      name: remote-kubeconfig    
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-configmap


