---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-s3reader
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-recommender
  interval: 21s
  path: ./deploy/crossplane-applications/s3reader
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-source
  kubeConfig:
    secretRef:
      name: remote-kubeconfig     
  healthChecks:
  - kind: Deployment
    name: s3-reader
    namespace: nodejs      
  validation: client
