---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-deploy
  namespace: flux-system
spec:
  interval: 30s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: crossplane-source
  validation: client

